name: Java CI for BinSuchBaum

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Build BinSuchBaum with Ant
        run: ant -noinput -buildfile ./BinSuchBaum/build.xml
      - name: Create JavaDoc for Projekt
        run: ant -noinput -buildfile ./BinSuchBaum/build.xml doc